#ifndef CHARACTER_TEST_H
#define CHARACTER_TEST_H

void test1_character_create();
void test2_character_create();
void test1_character_get_id();
void test2_character_get_id();
void test1_character_set_name();
void test2_character_set_name();
void test3_character_set_name();
void test1_character_get_name();
void test2_character_get_name();
void test1_character_set_gdesc();
void test2_character_set_gdesc();
void test1_character_get_gdesc();
void test2_character_get_gdesc();
void test1_character_set_location();
void test2_character_set_location();
void test3_character_set_location();
void test1_character_get_location();
void test2_character_get_location();
void test1_character_set_health();
void test2_character_set_health();
void test3_character_set_health();
void test1_character_get_health();
void test2_character_get_health();
void test1_character_set_friendly();
void test2_character_set_friendly();
void test1_character_get_friendly();
void test2_character_get_friendly();
void test1_character_set_message();
void test2_character_set_message();
void test3_character_set_message();
void test1_character_get_message();
void test2_character_get_message();
void test1_character_set_following();
void test2_character_set_following();
void test1_character_get_following();
void test2_character_get_following();
void test1_character_set_damage();
void test2_character_set_damage();
void test1_character_get_damage();
void test2_character_get_damage();

#endif