#ifndef PLAYER_TEST_H
#define PLAYER_TEST_H

void test1_player_create();
void test2_player_create();
void test1_player_get_id();
void test2_player_get_id();
void test1_player_set_name();
void test2_player_set_name();
void test3_player_set_name();
void test1_player_get_name();
void test2_player_get_name();
void test1_player_set_location();
void test2_player_set_location();
void test3_player_set_location();
void test1_player_get_location();
void test2_player_get_location();
void test1_player_set_health();
void test2_player_set_health();
void test1_player_get_health();
void test2_player_get_health();
void test1_player_add_object();
void test2_player_add_object();
void test3_player_add_object();
void test1_player_remove_object();
void test2_player_remove_object();
void test1_player_has_object();
void test2_player_has_object();
void test3_player_has_object();
void test1_player_set_gdesc();
void test2_player_set_gdesc();
void test1_player_get_gdesc();
void test2_player_get_gdesc();
void test1_player_set_damage();
void test2_player_set_damage();
void test1_player_get_damage();
void test2_player_get_damage();
void test1_player_set_dtaken();
void test2_player_set_dtaken();
void test1_player_get_dtaken();
void test2_player_get_dtaken();
void test1_player_set_max_health();
void test2_player_set_max_health();
void test1_player_get_max_health();
void test2_player_get_max_health();
void test1_player_set_max_turn();
void test2_player_set_max_turn();
void test1_player_get_max_turn();
void test2_player_get_max_turn();
void test1_player_set_n_turn();
void test2_player_set_n_turn();
void test1_player_get_n_turn();
void test2_player_get_n_turn();
void test1_player_set_teammate();
void test2_player_set_teammate();
void test1_player_get_teammate();
void test2_player_get_teammate();

#endif