#ifndef SPACE_TEST_H
#define SPACE_TEST_H

void test1_space_create();
void test2_space_create();
void test1_space_set_name();
void test2_space_set_name();
void test3_space_set_name();
void test1_space_get_id();
void test2_space_get_id();
void test1_space_get_name();
void test2_space_get_name();
void test1_space_set_object();
void test2_space_set_object();
void test1_space_get_object();
void test2_space_get_object();
void test1_space_add_object();
void test2_space_add_object();
void test3_space_add_object();
void test1_space_remove_object();
void test2_space_remove_object();
void test3_space_remove_object();
void test1_space_has_object();
void test2_space_has_object();
void test3_space_has_object();
void test1_space_add_character();
void test2_space_add_character();
void test3_space_add_character();
void test1_space_remove_character();
void test2_space_remove_character();
void test3_space_remove_character();
void test1_space_has_character();
void test2_space_has_character();
void test3_space_has_character();
void test1_space_get_character();
void test2_space_get_character();
void test1_space_set_gdesc_at();
void test2_space_set_gdesc_at();
void test3_space_set_gdesc_at();
void test1_space_get_gdesc_at();
void test2_space_get_gdesc_at();
void test3_space_get_gdesc_at();
void test1_Space_discovered();
void test2_Space_discovered();
void test1_space_get_discovered();
void test2_space_get_discovered();
void test3_space_get_discovered();

#endif